### ISSUE TITLE
spartanize code

### ISSUE THREAD

**Issue by igorbash** [TechnionYP5779/Team5-Diet-Tracker#118]
Check code is not broken after spartanizing

**Comment by igorbash** [comment]
spartanized my files.
can see in the commit:
https://github.com/TechnionYP5779/Team5-Fitnesspeaker/commit/5d65aa01c75e414b7e543b413e9009cc753e36da

**Comment by orfeld415** [comment]
https://github.com/TechnionYP5779/Team5-Fitnesspeaker/commit/5c1854b566ba6a3c5c0d8ccb058b24ab06e2a35f

**Comment by shaked-sapir** [comment]
spartnized mine and some other modules.
64a4a14b6287bf5670e14adf0bd5e323b28fea22
