### ISSUE TITLE
Algorithm fixing according to versions comparison - related to #152

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/Team5-Diet-Tracker#158]
In relation to #152 
Of course, we'll have to fix our algorithm accordingly.

- [x] normalize the freeText of the portion into a single form, so it could be captured in both single/plural form

- [x] normalize the units of the portion into a single form, so it could be captured in both single/plural form when matching to the label in USDA

- [x] handle the case of errors - i.e. when there are no results at all / none of the results passed the threshold

- [x] beside the 5 "no raw" results and the 2 "raw" results in Standard Reference mode, allow 2 results from branded mode, so the algorithm won't miss results because of lacking the brands

**Comment by shalev-kuba** [comment]
please see this link: http://www.java2s.com/Tutorial/Java/0040__Data-Type/Transformswordstosingularpluralhumanizedhumanreadableunderscorecamelcaseorordinalform.htm

**Comment by shaked-sapir** [comment]
after messing around with a couple of string inflectors and testing out a lot of different options, it turns out that turning the plural form into single using inflectors might cost us in accuracy, because the derivative rules arent fine enough.
Now I found out that the USDA converts plural to single automatically, so the first two missions are done.

**Comment by shalev-kuba** [comment]
i see you already handled the third issue, so i'm closing this issue
